#!/usr/bin/env bash
# post-checkout hook:
#  - auto-trust RTK project filters in this worktree, so the "[rtk] WARNING:
#    untrusted project filters" prefix does not appear in commit messages
#    generated by generate_lift_commit.py;
#  - create CLAUDE.md as a symlink to AGENTS.md when it is absent (CLAUDE.md is
#    untracked and git-ignored by design; the two files must stay identical).
REPO_ROOT="$(git rev-parse --show-toplevel)"
if [ -f "$REPO_ROOT/.rtk/filters.toml" ] && command -v rtk >/dev/null 2>&1; then
    rtk trust >/dev/null 2>&1 || true
fi
if [ -f "$REPO_ROOT/AGENTS.md" ] && [ ! -e "$REPO_ROOT/CLAUDE.md" ] && [ ! -L "$REPO_ROOT/CLAUDE.md" ]; then
    ln -s AGENTS.md "$REPO_ROOT/CLAUDE.md" 2>/dev/null || true
fi
exit 0
